### ISSUE TITLE
readrc v1 tracking

### ISSUE THREAD

**Issue by s3ththompson** [s3ththompson/readrc#1]
Tracking issue for v1 release:

- [x] API design
- [x] scaffold readrc object
- [x] migrate to streams 
- [x] add RSS support
- [x] implement first custom scraper
- [x] test end-to-end pipeline 
- [x] add disk caching
- [ ] decide default sources
- [ ] finalize post object, readrc config
- [ ] implement filter system, run in series
- [ ] design default layout
- [ ] implement frontend panel, c.f. [panel.enoki.site](http://panel.enoki.site/) 
- [ ] implement dat hosting
- [ ] add default filters
- [ ] add tests
- [ ] add docs
- [ ] robust examples
